### ISSUE TITLE
Having problems. 

### ISSUE THREAD

**Issue by wobstyr** [cfsimplicity/gocardless-legacy-cfml#4]
It seems the API has changed and this is component no longer works. are you going to release a new version of it? 
Thanks
Rob

**Comment by cfsimplicity** [comment]
Hi Rob.  I built this library for what is now their "legacy" API, but it does still work against that. See the docs at https://developer.gocardless.com/legacy

I need to look at their new API, but assuming it's straightforward then yes I will produce a new version of the client library, hopefully fairly soon. If you "watch" the repo then you'll get notifications of progress.

Cheers
Julian.

**Comment by wobstyr** [comment]
HI Julian

Thank you so much for getting back to me, I was not expecting that at all. Seems after the death of riaforge you can’t get many resources on coldfusion anymore.

Great I will be looking out for you update.

Have an awesome day

Rob

**Comment by cfsimplicity** [comment]
Rob, are you using Adobe ColdFusion as your CF engine? I've switched to Lucee only now so if you're still using ACF then it'd be useful if you could help test the new version for me when it's ready.

**Comment by wobstyr** [comment]
Hi Julian

Yes I am using CF11 on development and CF9 on production, will be implementing CF2016 on all systems soon.

Yes I would love to help in any way I can and if you need help debugging or developing I can help you there too.

Thanks
Rob

**Comment by cfsimplicity** [comment]
Hi Rob, just to update you - I've made a start on the new version, but the API is radically different so I'm having to build it all up from scratch. I've focused first on the new ["redirect flow" endpoint](https://developer.gocardless.com/api-reference/#core-endpoints-redirect-flows) as that's closest to the way the previous API worked and assumes you're not hosting your own approved payment pages. Is that what you intend to use? Which are the priority endpoints for you?

**Comment by cfsimplicity** [comment]
Hi Rob, just to let you know I've released my [new CFML library for the current Pro API](https://github.com/cfsimplicity/gocardless-pro-cfml). It covers all the core endpoints, but doesn't yet handle webhooks. I plan to add support for that soon.

There's a test suite which I've run on Lucee 4.5, 5.1 and ACF11.

Any feedback welcome.
